### ISSUE TITLE
Loading chunks past 33,554,432 blocks causes a crash

### ISSUE THREAD

**Issue by muzikbike** [PercyDan54/BorderRemover#5]
[22:54:06] [Render thread/FATAL]: Error executing task on Client
java.lang.IllegalArgumentException: Start element (9223372036853727232) is larger than end element (-9223372036854775808)
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet$Subset.<init>(LongAVLTreeSet.java:1117) ~[fastutil-8.2.1.jar:?]
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet.subSet(LongAVLTreeSet.java:1078) ~[fastutil-8.2.1.jar:?]
	at net.minecraft.class_5573.method_31771(class_5573.java:85) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5573.method_31772(class_5573.java:74) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5573.method_31782(class_5573.java:89) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5582.method_31869(class_5582.java:90) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_638.method_23782(class_638.java:215) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_631.method_16020(class_631.java:117) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_634.method_11128(class_634.java:664) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2672.method_11528(class_2672.java:96) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2672.method_11054(class_2672.java:22) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1075) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[22:54:11] [Render thread/FATAL]: Unreported exception thrown!
java.lang.IllegalArgumentException: Start element (9223367638808264704) is larger than end element (-9223372036854775808)
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet$Subset.<init>(LongAVLTreeSet.java:1117) ~[fastutil-8.2.1.jar:?]
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet.subSet(LongAVLTreeSet.java:1078) ~[fastutil-8.2.1.jar:?]
	at net.minecraft.class_5573.method_31777(class_5573.java:56) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5573.method_31783(class_5573.java:123) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5578.method_31807(class_5578.java:42) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1937.method_8333(class_1937.java:610) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1675.method_18075(class_1675.java:53) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_757.method_3190(class_757.java:613) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:986) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:810) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1112) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[22:54:11] [Server thread/INFO]: Stopping server
[22:54:11] [Server thread/INFO]: Saving players
[22:54:11] [Server thread/INFO]: MuzikBike lost connection: Disconnected
[22:54:11] [Server thread/INFO]: MuzikBike left the game
[22:54:11] [Server thread/INFO]: Stopping singleplayer server as player logged out
[22:54:11] [Server thread/INFO]: Saving worlds
[22:54:11] [Server thread/INFO]: Saving chunks for level 'ServerLevel[33554432test]'/minecraft:overworld
[22:54:13] [Server thread/ERROR]: Exception stopping the server
java.lang.IllegalArgumentException: Start element (9223372036853727232) is larger than end element (-9223372036854775808)
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet$Subset.<init>(LongAVLTreeSet.java:1117) ~[fastutil-8.2.1.jar:?]
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet.subSet(LongAVLTreeSet.java:1078) ~[fastutil-8.2.1.jar:?]
	at net.minecraft.class_5573.method_31771(class_5573.java:85) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5573.method_31772(class_5573.java:74) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5573.method_31782(class_5573.java:89) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5579.method_31812(class_5579.java:273) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5579.method_31842(class_5579.java:388) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at it.unimi.dsi.fastutil.longs.LongCollection.removeIf(LongCollection.java:197) ~[fastutil-8.2.1.jar:?]
	at net.minecraft.class_5579.method_31836(class_5579.java:386) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_3218.method_14176(class_3218.java:708) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:583) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:624) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1132.method_3782(class_1132.java:212) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:734) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 16/11/2021, 22:54
Description: Unexpected error

java.lang.IllegalArgumentException: Start element (9223367638808264704) is larger than end element (-9223372036854775808)
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet$Subset.<init>(LongAVLTreeSet.java:1117)
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet.subSet(LongAVLTreeSet.java:1078)
	at net.minecraft.class_5573.method_31777(class_5573.java:56)
	at net.minecraft.class_5573.method_31783(class_5573.java:123)
	at net.minecraft.class_5578.method_31807(class_5578.java:42)
	at net.minecraft.class_1937.method_8333(class_1937.java:610)
	at net.minecraft.class_1675.method_18075(class_1675.java:53)
	at net.minecraft.class_757.method_3190(class_757.java:613)
	at net.minecraft.class_757.method_3188(class_757.java:986)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet$Subset.<init>(LongAVLTreeSet.java:1117)
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet.subSet(LongAVLTreeSet.java:1078)
	at net.minecraft.class_5573.method_31777(class_5573.java:56)
	at net.minecraft.class_5573.method_31783(class_5573.java:123)
	at net.minecraft.class_5578.method_31807(class_5578.java:42)
	at net.minecraft.class_1937.method_8333(class_1937.java:610)
	at net.minecraft.class_1675.method_18075(class_1675.java:53)
	at net.minecraft.class_757.method_3190(class_757.java:613)
	at net.minecraft.class_757.method_3188(class_757.java:986)

-- Affected level --
Details:
	All players: 1 total; [class_746['MuzikBike'/24, l='ClientLevel', x=33554407.01, y=4.00, z=-15.68]]
	Chunk stats: 121, 60
	Level dimension: minecraft:overworld
	Level spawn location: World: (80,4,112), Section: (at 0,4,0 in 5,0,7; chunk contains blocks 80,0,112 to 95,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3094 game time, 3094 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.2, Eclipse Foundation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Foundation
	Memory: 2024426432 bytes (1930 MiB) / 3024093184 bytes (2884 MiB) up to 8480882688 bytes (8088 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 2112.00
	Graphics card #0 deviceId: 0x0152
	Graphics card #0 versionInfo: DriverVersion=10.18.10.5161
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Virtual memory max (MB): 14339.42
	Virtual memory used (MB): 7831.12
	Swap memory total (MB): 6253.88
	Swap memory used (MB): 143.58
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8085m
	Fabric Mods: 
		borderremover: Border Remover 1.0.3
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config2: Cloth Config v4 4.12.41
		fabric: Fabric API 0.42.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
		fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+6d0fac4218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+6d0fac4218
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+6d0fac4218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
		fabricloader: Fabric Loader 0.11.7
		java: OpenJDK 64-Bit Server VM 16
		minecraft: Minecraft 1.17.1
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 2500 GL version 3.2.0 - Build 10.18.10.5161, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fabulous
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz
	Player Count: 1 / 8; [class_3222['MuzikBike'/24, l='ServerLevel[33554432test]', x=33554407.01, y=4.00, z=-15.68]]
	Data Packs: vanilla, Fabric Mods

**Comment by PercyDan54** [comment]
This is a Minecraft issue
https://bugs.mojang.com/browse/MC-218504

**Comment by muzikbike** [comment]
Would this be fixable by the mod?

**Comment by PercyDan54** [comment]
> Would this be fixable by the mod?

Will try to do so if I have time

**Comment by PercyDan54** [comment]
The problematic function (called with y and z = 0):
```JAVA
   public static long asLong(int x, int y, int z) {
      long i = 0L;
      i |= ((long)x & 4194303L) << 42;
      i |= ((long)y & 1048575L);
      return i | ((long)z & 4194303L) << 20;
   }
```

Since I'm suck at math and bit wise operation, I needed someone to help

**Comment by Cyclopropinon** [comment]
> The problematic function (called with y and z = 0):
> 
> ```java
>    public static long asLong(int x, int y, int z) {
>       long i = 0L;
>       i |= ((long)x & 4194303L) << 42;
>       i |= ((long)y & 1048575L);
>       return i | ((long)z & 4194303L) << 20;
>    }
> ```
> 
> Since I'm suck at math and bit wise operation, I needed someone to help

@PercyDan54 what do u want the function to do?
(i know quite a bit math and bitwise operation, but idk if it suffices. plus im bad at java XD)

**Comment by MetsukiMio** [comment]
> > The problematic function (called with y and z = 0):
> > ```java
> >    public static long asLong(int x, int y, int z) {
> >       long i = 0L;
> >       i |= ((long)x & 4194303L) << 42;
> >       i |= ((long)y & 1048575L);
> >       return i | ((long)z & 4194303L) << 20;
> >    }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Since I'm suck at math and bit wise operation, I needed someone to help
> 
> @PercyDan54 what do u want the function to do? (i know quite a bit math and bitwise operation, but idk if it suffices. plus im bad at java XD)

compress position data(3 ints) to a long value, crash may caused by the limit(x/z = 4194304, y = 1048575, the number after the operand &)

**Comment by arcade-smasher** [comment]
This is technically fixable by this mod, but very infeasible. Here, we are packing 3 `int`s into one `long`. There is simply not enough space to pack 3 numbers potentially larger than 2^25 into one `long`. The only fix would be to pack them into a different struct like `BigInteger`, but that would not only significantly slow down the game, but also require extreme modification to every single class that interprets the `long` (which would now become a `BigInteger`). While this is technically doable, it is not feasible to do, and depending on how many classes interpret the `long`, this could take a _very_ long time to fix.
